### ISSUE TITLE
[Suggestion] S2 Cell overlay

### ISSUE THREAD

**Issue by elamhut** [MrJPGames/WayFarer-#18]
Any chance we could have:

S2 Cells overlay over the map
Specific Coordinates for the Wayspot

Amazing work! Thanks :D

**Comment by GoncaloCdM** [comment]
Implementing S2 cells over the map should not be difficult. I've tried, with success, using a google.maps.Polygon({ paths, fillColor, fillOpacity, strokeColor, strokeOpacity, strokeWeight }), where the paths come from the s2 Sidewalk Labs API. In fact, copying a few lines of code from their open source Region Coverer (available at https://s2.sidewalklabs.com/regioncoverer/) is more than enough. The difference is that instead of manually dragging a pin to the map, we get the provided Portal coordinates coming from the Nomination Controller.

**Comment by MrJPGames** [comment]
In 1.7.2 map buttons are persent on the review page, giving coordinates. Your own nomination have had this since 1.7.1

Thanks @GoncaloCdM for the pointers. This should speed up S2 cell development greatly!
Expect S2 support to be added soon(tm)

**Comment by GoncaloCdM** [comment]
You’re welcome, @MrJPGames! I sent you an email with a few suggestions. Can you please check that up?

**Comment by MrJPGames** [comment]
What email? I see none in my semi-private email address but I've gotten a few...

**Comment by GoncaloCdM** [comment]
The e-mail listed under your profile: jasper(…).
The subject is “Niantic Wayfarer Userscript”.

**Comment by GoncaloCdM** [comment]
It was sent on October 14, 2019.

**Comment by GoncaloCdM** [comment]
You can hit me up on Telegram (@GoncaloCdM) about that email.

**Comment by MrJPGames** [comment]
Implemented in 07b985d4b99c4edca7423836f1a5e71503c0f99b
