### ISSUE TITLE
Review Stats math is not correct

### ISSUE THREAD

**Issue by tehstone** [MrJPGames/WayFarer-#20]
Not sure what exactly is being calculated but the math is incorrect on the extended stats.

This album shows stats with and without the extended stats.
https://imgur.com/a/LIelfEZ

**Comment by MrJPGames** [comment]
It's because you have not redeemed all upgrades you've ever gotten. There is currently no way to fix this, as all this information has to be inferred from the information available on the regular page. 

For the time being I recommend you turn off extended profile stats all together as they add nothing in your case.

There might be an additional ingress badge progress stat which will work always, so because I am now aware of this issue I will make sure it is a separate setting!

This also indicates to me that more transparency can go a long way, an update with explanations for all of the settings should also help similar cases in the future hopefully!

Thanks for reporting!

**Comment by MrJPGames** [comment]
To clarify this issue will remain open until I have taken measures to communicate more clearly to all users why this happens. As well as hopefully preemptively solving similar cases with other mods.

**Comment by tehstone** [comment]
Ah ok. So this must be because I had so many agreements before upgrades were introduced. That makes sense now.

**Comment by tehstone** [comment]
`Processed and Agreement 19142`

Where is this number coming from? Does the page somehow know how many agreements I've had "post-upgrades" ? 

My assumption would be that that number is just the sum of "Wayspots Accepted" and "Nominations Rejected"

**Comment by MrJPGames** [comment]
Processed and Agreement is:
(upgrades_used+upgrades_available)*100+current_upgrade_progress

The upcoming ingress badge progress will be the sum of accepted+rejected

**Comment by tehstone** [comment]
Ok. I guess that makes sense, but obviously for anyone like me who had agreements prior to the introduction of Upgrades these numbers will be forever incorrect.

Overall I like the plugin, thanks for the hard work!
